In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
x = np.random.randint(1,100, (6,6))

In [7]:
print(x)

[[35 32 25  4 34 16]
 [83 60 73 62 94 13]
 [73 13 71  9 32 39]
 [50 96 54 89 75 12]
 [89  9 83 14 52 91]
 [43 22 12 62 41 78]]


In [8]:
x[0]

array([35, 32, 25,  4, 34, 16])

In [5]:
x[0,1]

19

In [9]:
x[:, 0] # first column

array([35, 83, 73, 50, 89, 43])

In [10]:
x[:, 4]

array([34, 94, 32, 75, 52, 41])